module.exports = {
  RESPONSE_CODE_OK: 200,
  HEADER_CONTENT_TYPE: 'Content-Type',
  HEADER_CONTENT_TYPE_JSON: 'application/json',
  HEADER_CONTENT_TYPE_TEXT: 'text/plain',
  HEADER_CONTENT_TYPE_HTML: 'text/html',
  HEADER_CONTENT_TYPE_XML: 'text/xml',

  TYPE_JSON: 'JSON',
  TYPE_TEXT: 'TEXT',
  TYPE_HTML: 'HTML',
  TYPE_XML: 'XML',
  TYPE_BINARY: 'BINARY',
  TYPE_ERROR: 'ERROR',
};
